name: replace-in-files
files:
  - '.*'
  - '*'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /monorepo-lerna-description/g
    to: React command manager.
  - from: /monorepo-lerna/g
    to: ${PROJECT_NAME}
